### ISSUE TITLE
Error pri zagonu

### ISSUE THREAD

**Issue by AnaMarijaB** [AnaMarijaB/APPR-2019-20#3]
Že pri zagonu libraries se mi pokaže napaka 

Error: package or namespace load failed for ‘readr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘vctrs’ 0.2.0 is already loaded, but >= 0.2.1 is required

Pogledala sem po kaj bi lahko naredila. Poskušala sem na novo inštalirat package readr, vendar še vedno ne deluje. 

Glede na to da mi program zažene preko binderja je napaka samo tukaj. Rada bi dodala še aplikacijo shiny, potem pa mislim da sem pri koncu.

**Comment by jaanos** [comment]
Po napaki sodeč bi predlagal, da znova namestiš knjižnico `vctrs`. Če po tem dobiš podobno napako z drugimi knjižnicami, poskusi namestiti še te.
